services:
  db_catalogue:
    container_name: db_catalogue
    image: postgres:latest
    environment:
      POSTGRES_USER: catalogue
      POSTGRES_PASSWORD: catalogue
      POSTGRES_DB: catalogue
    ports:
      - "5432:5432"

  db_manager:
    container_name: db_manager
    image: postgres:latest
    environment:
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: manager
      POSTGRES_DB: manager
    ports:
      - "5433:5432"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
    volumes:
      - type: bind
        source: ./config/keycloak/import/realm-export.json
        target: /opt/keycloak/data/import/realm-export.json
    ports:
      - "8082:8080"
    depends_on:
      - postgres
volumes:
  postgres-data: